# Enable automatic preview environments for every pull request
previews:
  generation: automatic

# Define your web service
services:
  - type: web
    name: prodpulse-api
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: gunicorn prodpulse_api.wsgi:application --bind 0.0.0.0:$PORT

    # Link the managed database
    databases:
      - prodpulse-db

    # Expose environment variables
    envVars:
      - key: DATABASE_URL
        value: postgres://user:pass@hostname:5432/dbname

      - key: DJANGO_SETTINGS_MODULE
        value: prodpulse_api.settings

      - key: SECRET_KEY
        sync: false

# Provision a Postgres database for ProdPulse
databases:
  - name: prodpulse-db
    engine: postgresql
    plan: starter